# Generated by Django 4.2 on 2024-05-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile_riot_puuid_profilesocials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesocials',
            name='network',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube'), ('Discord', 'Discord'), ('Steam', 'Steam')], max_length=100),
        ),
    ]
