# Generated by Django 4.2 on 2024-05-14 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tournament_description_tournament_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.game'),
        ),
    ]
